name: Test MacOSX
run-name: ${{ github.actor }} 
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run : brew install gcc@11
    
    - name: Build model
      run: |
        make PHYSICELL_CPP=g++-11
        make invasive_carcinoma PHYSICELL_CPP=g++-11
        make fibrosis PHYSICELL_CPP=g++-11
        
    - name: Run model
      run: |
        ./AMIGOS-invasion config/simple_test2_random_1_D_circles.xml
        ./AMIGOS-invasion config/leader_follower_model_test.xml
        ./invasive_carcinoma config/invasive_carcinoma_test.xml
        ./fibrosis config/fibrosis_test.xml
