name: Test Ubuntu
run-name: ${{ github.actor }} 
on:
  push:
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Build model
      run: |
        make
        
    - name: Run model
      run: |
        .\\AMIGOS-invasion
