name: Test Ubuntu
run-name: ${{ github.actor }} 
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Build model
      run: |
        make
        
    - name: Build model
      run: |
        make
        make invasive_carcinoma
        make fibrosis
        
    - name: Run model
      run: |
        ./AMIGOS-invasion config/simple_test2_random_1_D_circles.xml
        ./AMIGOS-invasion config/leader_follower_model_test.xml
        ./invasive_carcinoma config/invasive_carcinoma_test.xml
        ./fibrosis config/fibrosis_test.xml
